function [method, bits] = char_config
%%
global setups
fig = uifigure('Name', 'Configuration', 'Position', [680 558 480 200]);
panel = uipanel(fig);
panel.Position = fig.Position .* [0 0 1 1] + [20 20 -40 -40];
bg = uibuttongroup(panel,...
                  'Title','Fiber Span',...
                  'Position', [20 60 120 80]);
% Create three radio buttons in the button group.
uiradiobutton(bg,...
                  'Text','Back-to-Back',...
                  'UserData','syncd_b2b_brief',...
                  'Position',[15 35 100 15]);              
uiradiobutton(bg,...
                  'Text','20km SSMF',...
                  'UserData','syncd',...
                  'Position',[15 15 100 15]);
              
bg2 = uibuttongroup(panel,...
                  'Title','Switching',...
                  'Position', [160 60 120 80]);
uiradiobutton(bg2,...
                  'Text','PISIC',...
                  'UserData','pisic',...
                  'Position',[15 35 100 15]);              
uiradiobutton(bg2,...
                  'Text','MISIC',...
                  'UserData','misic',...
                  'Position',[15 15 100 15]);
              
bg3 = uibuttongroup(panel,...
                  'Title','Impulse bits',...
                  'Position', [300 40 120 100]);
% Create three radio buttons in the button group.
uiradiobutton(bg3,...
                  'Text','16ps',...
                  'UserData',2,...
                  'Position',[15 55 100 15]);
uiradiobutton(bg3,...
                  'Text','32ps',...
                  'UserData',4,...
                  'Position',[15 35 100 15]);
uiradiobutton(bg3,...
                  'Text','64ps',...
                  'UserData',8,...
                  'Position',[15 15 100 15]);
              
uilabel(fig,...
    'Position', panel.Position .* [.5 0 0 0] + [30 50 250 20],...
    'Text','Select characterization scope:');

uibutton(panel,'Text','Single',...
                  'Position', panel.Position .* [.5 0 0 0] + [10 10 50 20],...
                  'ButtonPushedFcn', @(btn,event) plotButtonPushed(fig,bg,bg2,bg3));
% btn2 = uibutton(panel,'Text','Whole',...
%                   'Position', panel.Position .* [.5 0 0 0] + [70 10 50 20],...
%                   'ButtonPushedFcn', @(btn2,event) plotButtonPushed2(fig,bg,bg2,bg3));
uiwait(fig);
% 
% method = setups.method;
% bits = setups.bits;
end

function plotButtonPushed(fig,bg,bg2,bg3)
    global setups;
    setups.method = {bg.SelectedObject.UserData,bg2.SelectedObject.UserData};
    setups.bits = bg3.SelectedObject.UserData;
%     setups.scope = 'single';
    delete(fig);
end

% function plotButtonPushed2(fig,bg,bg2,bg3)
%     global setups;
%     setups.method = {bg.SelectedObject.UserData,bg2.SelectedObject.UserData};
%     setups.bits = bg3.SelectedObject.UserData;
%     setups.scope = 'whole';
%     delete(fig);
% end